### 21.02.2022
# Modules

## Intro to Modules

In [5]:
import calendar
year1 = calendar.prcal(2022)
print(year1)

                                  2022

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 

In [6]:
from calendar import prcal
year2 = prcal(2020)
print(year2)

                                  2020

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                         1
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       2  3  4  5  6  7  8
13 14 15 16 17 18 19      10 11 12 13 14 15 16       9 10 11 12 13 14 15
20 21 22 23 24 25 26      17 18 19 20 21 22 23      16 17 18 19 20 21 22
27 28 29 30 31            24 25 26 27 28 29         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 

In [3]:
# Ecercise 33
import random
computer_choice = random.randint(0, 100)
print(f"That is a computer choice: {computer_choice}")
print("")
print("There is a number you have to guess!")
print("")
your_choice = int(input("What is your first guess: "))


i = 1
while your_choice != computer_choice:
    your_choice = int(input("Next guess: "))
    if your_choice > computer_choice:
        print("Give a smaller number")
        i += 1
    elif your_choice < computer_choice:
        print("Give a bigger number")
        i += 1
    else:
        print("You guessed correctly!")
        i += 1
        #print(i)
print(f"Number of your attempts: {i}")

That is a computer choice: 32

There is a number you have to guess!

What is your first guess: 22
Next guess: 32
You guessed correctly!
Number of your attempts: 2


## OS

In [6]:
import os
os.system("clear")

0

In [13]:
os.system("ls -la")

total 176
drwxr-xr-x  13 vera  staff    416 Feb 21 13:37 .
drwxr-xr-x   3 vera  staff     96 Feb 14 09:06 ..
drwxr-xr-x  12 vera  staff    384 Feb 18 22:33 .git
-rw-r--r--   1 vera  staff     19 Feb 18 22:21 .gitignore
drwxr-xr-x   4 vera  staff    128 Feb 21 12:42 .ipynb_checkpoints
-rw-r--r--   1 vera  staff  14535 Feb 21 11:49 functions.ipynb
-rw-r--r--   1 vera  staff   3308 Feb 18 22:06 functions.py
-rw-r--r--   1 vera  staff   5417 Feb 14 15:33 lists.py
-rw-r--r--   1 vera  staff   6470 Feb 16 22:09 lists_dictionaries.py
-rw-r--r--   1 vera  staff  21909 Feb 18 15:08 loops.ipynb
-rw-r--r--   1 vera  staff   9949 Feb 21 13:35 modules.ipynb
-rw-r--r--   1 vera  staff   5542 Feb 16 21:35 nested_dictionaries.ipynb
-rw-r--r--   1 vera  staff   2896 Feb 16 21:47 sets_tuples.py


0

In [17]:
os.mkdir("test_os_module")
os.system("ls -la")
#os.chdir("test_os")

total 176
drwxr-xr-x  14 vera  staff    448 Feb 21 13:39 .
drwxr-xr-x   3 vera  staff     96 Feb 14 09:06 ..
drwxr-xr-x  12 vera  staff    384 Feb 18 22:33 .git
-rw-r--r--   1 vera  staff     19 Feb 18 22:21 .gitignore
drwxr-xr-x   4 vera  staff    128 Feb 21 12:42 .ipynb_checkpoints
-rw-r--r--   1 vera  staff  14535 Feb 21 11:49 functions.ipynb
-rw-r--r--   1 vera  staff   3308 Feb 18 22:06 functions.py
-rw-r--r--   1 vera  staff   5417 Feb 14 15:33 lists.py
-rw-r--r--   1 vera  staff   6470 Feb 16 22:09 lists_dictionaries.py
-rw-r--r--   1 vera  staff  21909 Feb 18 15:08 loops.ipynb
-rw-r--r--   1 vera  staff  10205 Feb 21 13:37 modules.ipynb
-rw-r--r--   1 vera  staff   5542 Feb 16 21:35 nested_dictionaries.ipynb
-rw-r--r--   1 vera  staff   2896 Feb 16 21:47 sets_tuples.py
drwxr-xr-x   2 vera  staff     64 Feb 21 13:39 test_os_module


0

In [16]:
os.system("rm -r test_os_module")


0

In [7]:
os.getcwd()

'/Users/vera/Desktop/CQ/Python/My_py/PythonDataStructures'

In [23]:
Dirs = ["Hello", "Hi"]
for Dir in Dirs:
    #os.mkdir(Dir) # an easier way
    os.system("mkdir " + Dir)
    

In [35]:
!ls

Hello                     lists.py                  nested_dictionaries.ipynb
Hi                        lists_dictionaries.py     sets_tuples.py
functions.ipynb           loops.ipynb               test_os
functions.py              modules.ipynb


In [29]:
os.makedirs("test_os/hello/world", exist_ok = True)


In [39]:
!rm -r test_os

!ls


functions.ipynb           lists_dictionaries.py     nested_dictionaries.ipynb
functions.py              loops.ipynb               sets_tuples.py
lists.py                  modules.ipynb


In [115]:
# Exercise 34
curdir = "/Users/vera/Desktop/CQ/Python/My_py/PythonDataStructures/structure/sub_str"
import os
#os.mkdir("structure")
#os.makedirs("structure/sub_str")
#os.chdir("structure/sub_str")
folders = ["fld1", "fld2", "fld3", "fld4", "fld5"]
for fld in folders:
    os.mkdir(fld)
    os.chdir(fld)
    os.system("touch file.txt")
    os.chdir(curdir)

## Math

In [124]:
import math
var1 = 12
var2 = 5
print(math.isnan(var1))
print(math.pow(var1, var2))

False
248832.0


In [128]:
def math_ops(a,b):
    print("a^b =")
    return math.pow(a,b)

inp1 = int(input("Type the first number"))
inp2 = int(input("Type the second number"))

math_ops(inp1, inp2)

Type the first number2
Type the second number3
a^b =


8.0

In [146]:
inp1 = int(input("Type the first number: "))
inp2 = int(input("Type the second number: "))
print(math.exp(inp1))
#print(math.log(inp1, inp2))
print(math.log2(inp1))
print(math.log10(inp1))
print(math.pow(inp1, inp2))
print(math.sqrt(inp1))
print(math.cos(inp1))
print(math.sin(inp1))
print(math.tan(inp1))
if inp1 >= -1 and inp2 <=1: 
    print(math.acos(inp1)) # -1 < x < 1
    print(math.asin(inp1))
    print(math.atan(inp1))

Type the first number: 1
Type the second number: 1
2.718281828459045
0.0
0.0
1.0
1.0
0.5403023058681398
0.8414709848078965
1.557407724654902
0.0
1.5707963267948966
0.7853981633974483


In [114]:
# Exercise 36
import math
inp1 = int(input("Type the first number: "))
inp2 = int(input("Type the second number: "))
inp3 = int(input("Select a constat: 1 - Pi, 2 - Euler, 3 - Tau: "))
if inp3 not in range(1,4):
    print("You selection is not correct. Select option 1, 2 or 3.")
elif inp3 == 1 or inp3 == 2 or inp3 ==3: 
    inp1 = inp1*math.pi
    inp2 = inp2*math.pi
    inp1 = inp1*math.e
    inp2 = inp2*math.e
    inp1 = inp1*math.tau
    inp2 = inp2*math.tau

print(math.exp(inp1))
if inp2 > 1:
    print(math.log(inp1, inp2))
print(math.log2(inp1))
print(math.log10(inp1))
if inp1 != 0 and inp2 != 0:
    print(math.pow(inp1, inp2))
print(math.sqrt(inp1))
print(math.cos(inp1))
print(math.sin(inp1))
print(math.tan(inp1))
if inp1 >= -1 and inp1 <=1: 
    print(math.acos(inp1)) # -1 < x < 1
    print(math.asin(inp1))
    print(math.atan(inp1))

Type the first number: 3
Type the second number: 4
Select a constat: 1 - Pi, 2 - Euler, 3 - Tau: 4
You selection is not correct. Select option 1, 2 or 3.
20.085536923187668
0.7924812503605781
1.584962500721156
0.47712125471966244
81.0
1.7320508075688772
-0.9899924966004454
0.1411200080598672
-0.1425465430742778


In [21]:
# Exercise 37
import random
my_list = []

i = 0
number = True
while i < 3:
    start = int(input("Define left range border: "))
    stop = int(input("Define right range border: ")) -1
    number = random.randint(start, stop)
    print(number)
    my_list.append(number)
    i += 1

how_many = int(input("How many floats between 0 and 1 do you want: "))
for j in range(how_many):
    #print(round(random.random(),2))
    my_list.append(round(random.random(),2))

k = 0
while k < 2:
    mu = int(input("Type a population avarage:  "))
    sigma = int(input("Type a population standard deviation: "))
    print(round(random.gauss(mu, sigma)),2)
    my_list.append(round(random.gauss(mu, sigma),2))
    k += 1

print(my_list)
random.shuffle(my_list) # takes lists as an input
print(my_list)

Define left range border: 33
Define right range border: 1000
164
Define left range border: 22
Define right range border: 300
27
Define left range border: 222
Define right range border: 10000
4106
How many floats between 0 and 1 do you want: 3
0.35
0.35
0.57
Type a value for a population avarage:  222
Type a value for a population standard deviation: 2
219 2
Type a value for a population avarage:  333
Type a value for a population standard deviation: 3
337 2
[164, 27, 4106, 0.74, 0.79, 0.77, 219.81, 336.41]


[164, 27, 219.81, 0.79, 336.41, 4106, 0.74, 0.77]

## NumPy

In [47]:
import numpy as np
my_array1 = np.array([5,6,7,8])
print(my_array1)
my_array2 = np.ones(5)
print(my_array2)
my_array3 = np.zeros(5)
print(my_array3)
my_array4 = np.arange(15)
print(my_array4)
my_array5 = np.arange(15).reshape(3,5)
print(my_array5)
my_array6 = np.random.randn(4,6) # 4 - number of sublists, 6 - number of elements in each sublist
print(my_array6)
sum1 = my_array1.sum()
print(sum1)
min1 = my_array1.max()
print(min1)
print(my_array5.transpose())
my_array5[1][1] # [row][col]

[5 6 7 8]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[-1.20401136 -0.96096832 -1.21795163 -0.46560677  1.33555129  0.94856367]
 [-0.33877693 -0.42661309  0.21826881 -0.78842502 -1.10691231  0.91442512]
 [ 0.66904372  1.21022544 -0.30448727  0.90852909 -0.20151966  0.33997591]
 [ 0.78323646 -0.51210607  0.92852908  0.92112588  0.72921193  0.04250813]]
26
8
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


6

In [108]:
# Exercise 38
import numpy as np
ar_zeros = np.zeros(25).reshape(1,25)
print(ar_zeros)
ar_ones = np.ones(8).reshape(1,8)
print(ar_ones)
ar_arange = np.arange(25).reshape(1, 25)
print(ar_arange)
ar_choice = np.random.randint(0, 9, 9).reshape(1,9)
print(ar_choice)
td = np.arange(1,31).reshape(6,5)
print(td)
print("")
td_trsp = td.transpose()
print(td_trsp)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
[[4 6 5 5 1 0 2 1 3]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [111]:
arrays = [ar_zeros, ar_ones, ar_arange, ar_choice, td, td_trsp]
print(arrays)
for array in arrays:
    print(f"This is a sum for array {array}: {array.sum()}")
    print(f"This a min for array {array}: {array.min()}")
    print(f"This a max for array {array}: {array.max()}")
    a, b = np.shape(array)
    print(f"Number of rows in array {array}: {a}")
    print(f"Number of columns in array {array}: {b}")
    
        
        

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]]), array([[1., 1., 1., 1., 1., 1., 1., 1.]]), array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]]), array([[4, 6, 5, 5, 1, 0, 2, 1, 3]]), array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]]), array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])]
This is a sum for array [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]: 0.0
This a min for array [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]: 0.0
This a max for array [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]: 0.0
Number of row

## SciPy


In [115]:
# a collection math algorithms on top on NumPy
# linalg (linear algebra) and so on

## Pandas

In [117]:
import pandas as pd


In [127]:
df = pd.DataFrame(np.random.randint(0, 9, 8).reshape(2,4), index =["Test1", "Test2"], columns=list("ABCD"))

In [128]:
df

A  B  C  D
Test1  2  2  3  7
Test2  4  0  8  5

In [129]:
df.loc["Test1", "A"]

2

In [130]:
df.iloc[0][1]

2

In [132]:
df.loc["Test1", "A"] = 77
df

A  B  C  D
Test1  77  2  3  7
Test2   4  0  8  5

In [133]:
df.sum() # colomn-wise


A    81
B     2
C    11
D    12
dtype: int64

In [134]:
df.sum(axis=1) # row-wise

Test1    89
Test2    17
dtype: int64

In [172]:
df.index
for index in df.index:
    print(index)
for column in df.columns:
    print(column)

Test1
Test2
Test3
Test4
A
B
C
D
E
F


In [186]:
# Exercise 39
df1 = pd.DataFrame(np.random.random(24).reshape(4,6), index =["1", "2", "3", "4"], columns=list("ABCDEF"))
print("The original dataframe:")
print(df1)
print("*"*62)
print("The sorted dataframes:")
for column in df1.columns:
    print(f"Column {column}")
    print(df1.sort_values(column))
    print("*"*62)
print("Stat summary:")
print(df1.describe()) # statistical summary
    

The original dataframe:
          A         B         C         D         E         F
1  0.046686  0.234540  0.190130  0.360170  0.561667  0.666582
2  0.204602  0.387193  0.203753  0.571192  0.067615  0.046890
3  0.099931  0.624980  0.151681  0.338485  0.363460  0.328995
4  0.672283  0.936226  0.551569  0.158393  0.975755  0.130240
**************************************************************
The sorted dataframes:
Column A
          A         B         C         D         E         F
1  0.046686  0.234540  0.190130  0.360170  0.561667  0.666582
3  0.099931  0.624980  0.151681  0.338485  0.363460  0.328995
2  0.204602  0.387193  0.203753  0.571192  0.067615  0.046890
4  0.672283  0.936226  0.551569  0.158393  0.975755  0.130240
**************************************************************
Column B
          A         B         C         D         E         F
1  0.046686  0.234540  0.190130  0.360170  0.561667  0.666582
2  0.204602  0.387193  0.203753  0.571192  0.067615  0.046890
3  

In [188]:
from pandas_profiling import ProfileReport

In [191]:
profile = ProfileReport(df)
#profile